spring:
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63792}
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/offers-web
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

joboffers:
  offer:
    durationOfResponse: "* * */10 * * *"
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057
          connectionTimeout: 1000
          readTimeout: 1000

scheduling:
  enabled: true

auth:
  jwt:
    secret: ${JWT_SECRET}
    issuer: job-offers-backend
    expirationDays: 30